<a href="https://colab.research.google.com/github/heenamandalgithub/Python-Practice-Program/blob/main/Copy_of_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([4,5,6])
print(a)

[4 5 6]


In [ ]:
import numpy as np
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
import time 
import sys
S=range(100)
print(sys.getsizeof(5)*len(S))
D=np.arange(100)
print(D.size*D.itemsize)

2800
800


In [ ]:
import time
import sys
SIZE=10000
L1=range(SIZE)
L2=range(SIZE)
A1=np.arange(SIZE)
A2=np.arange8=(SIZE)
start=time.time()
result=[(x,y)for x,y in zip(L1,L2)]
print((time.time()-start)*100)
start=time.time()
result=A1+A2
print((time.time()-start)*100)

0.26161670684814453
0.07486343383789062


In [ ]:
import numpy as np
a=np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


In [ ]:
import numpy as np
a=np.array([(1,2,3,4,5)])
print(a.itemsize)

8


In [ ]:
import numpy as np
a=np.array([(1,2,3)])
print(a.dtype)

int64


In [ ]:
import numpy as np
a=np.array([(1,2,3,4,5)])
print(a.size)
print(a.shape)

5
(1, 5)
